name: "Deploy HexCalc"

on:
  push:
    branches:
      - main

env:
  PROJ_PATH: win64/HexCalc/HexCalc.csproj

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJ_PATH }}

    - name: Build the project
      run: dotnet build ${{ env.PROJ_PATH }} -c Release --no-restore

    - name: Publish the project
      run: dotnet publish ${{ env.PROJ_PATH }} -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true
